config/routes.rb
RoundfileApp::Application.routes.draw do

root :to => 'pages#home'

  resources :sections
  resources :users
  resources :resumes
  resources :resumesections
  resources :comments
  resources :ratings
  resources :sessions, :only => [:new, :create, :destroy]

	
	match '/newsection',  :to => 'sections#new'
	match '/mysections',  :to => 'sections#mysections'
	match '/newresume',  :to => 'resumes#new'
	match '/viewresume/:id',  :to => 'resumes#show'
	match '/newresume/:id', :to => 'resumesections#new'
	match '/newresumelist/:id', :to => 'resumesections#list'
	match '/newresume/:id/:message', :to => 'resumesections#new'
	match '/myresumes',  :to => 'resumes#myresumes'
	match '/signup',  :to => 'users#new'
	match '/signin',  :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/newcomment/:id',  :to => 'comments#new'
	match '/newcomment/:id/:message', :to => 'comments#new'
	match '/newrating/:id',  :to => 'ratings#new'
	match '/newrating/:id/:score', :to => 'ratings#new'
	match '/userresumes', :to => 'resumes#userres'
	match '/userresumes/:id/', :to => 'resumes#userres'
	
	

end

app/models/resumesection.rb
class Resumesection < ActiveRecord::Base

	attr_accessible :resumeid, :sectionid, :orderNum
	
	belongs_to :resume
	belongs_to :section, :class_name => 'Section', :foreign_key => 'sectionid'
	
	
	validates :resumeid, :presence => true
	validates :sectionid, :presence => true
	validates :orderNum, :presence => true
	
end




# == Schema Information
#
# Table name: resumesections
#
#  id         :integer         not null, primary key
#  resumeid   :integer
#  sectionid  :integer
#  orderNum   :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/resumesections_controller.rb
class ResumesectionsController < ApplicationController
 
	  
  def show
	@resumesection = Resumesection.find(params[:id])
	@title = "Show Resume Sections"
  end
  
  def new
	@title = "New Resume"
	if (!params[:message].blank?)
		flash[:error] = "There was an error adding this section to the resume. Make sure to select a section and enter an order number."
	end
	
	
	@resumesection = Resumesection.new
	
	if (@resumesection.resumeid != nil)
		params[:id] = @resumesection.resumeid
	end
	

	if (Section.find_all_by_userid_and_typesection(current_user.id, 'Contact') != nil)
		@myContact = Section.find_all_by_userid_and_typesection(current_user.id, 'Contact')
	end
	
	if(Section.find_all_by_userid_and_typesection(current_user.id, 'Objective') != nil)
		@myObjective = Section.find_all_by_userid_and_typesection(current_user.id, 'Objective')
	end
	
	if(Section.find_all_by_userid_and_typesection(current_user.id, 'Qualifications') != nil)
		@myQualifications = Section.find_all_by_userid_and_typesection(current_user.id, 'Qualifications')
	
	end
	
	if(Section.find_all_by_userid_and_typesection(current_user.id, 'Education') != nil)
		@myEducation = Section.find_all_by_userid_and_typesection(current_user.id, 'Education')
	
	end
	
	if(Section.find_all_by_userid_and_typesection(current_user.id, 'Skills') != nil)
		@mySkills =	Section.find_all_by_userid_and_typesection(current_user.id, 'Skills')
	
	end
	
	if(Section.find_all_by_userid_and_typesection(current_user.id, 'Employment History') != nil)
		@myEmplHistory = Section.find_all_by_userid_and_typesection(current_user.id, 'Employment History')
	
	end
	
	if(Section.find_all_by_userid_and_typesection(current_user.id, 'List of References') != nil)
		@myListRef = Section.find_all_by_userid_and_typesection(current_user.id, 'List of References')
	
	end
	
	if(Section.find_all_by_userid_and_typesection(current_user.id, 'Other') != nil)
		@myOther =	Section.find_all_by_userid_and_typesection(current_user.id, 'Other')
	
	end


	
  end
  
  
  def list
	@title = "Resume List"
	@resume = Resume.find(params[:id])
	@resumesection = Resumesection.find_all_by_resumeid(params[:id], :order => "orderNum")
	
	#code from DEMO APP
	respond_to do |format|
      format.html 
      format.xml  { render :xml => @resumesection }
    end

  end
  
  def create	
    @resumesection = Resumesection.new(params[:resumesection])
	
    if @resumesection.save
      flash[:success] = "Resume Section created!"
      redirect_to "/newresumelist/#{@resumesection.resumeid}"
    else
      @title = "New Resume"
	  redirect_to "/newresume/#{@resumesection.resumeid}/error"
      #render 'new'
	end
  end
  
  
  
  
  def edit
	@title = "Edit Order of Section"
    @resumesection = Resumesection.find(params[:id])
  end
  
  def update
	@title = "Edit Order of Section"

    @resumesection = Resumesection.find(params[:id])

    respond_to do |format|
      if @resumesection.update_attributes(params[:resumesection])
        format.html { redirect_to("/newresumelist/#{@resumesection.resumeid}", :notice => 'Order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @resumesection.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  
  def destroy

    @resumesection = Resumesection.find(params[:id])
	#@test = @resumesection.resumeid
    @resumesection.destroy

    respond_to do |format|
      format.html { redirect_to("/newresumelist/#{@resumesection.resumeid}") }
      format.xml  { head :ok }
    end
  end

  
end

app/helpers/resumesections_helper.rb
module ResumesectionsHelper

end

app/views/resumesections/_form.html.erb
<%= form_for(@resumesection) do |f| %>
  <% if @resumesection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resumesection.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @resumesection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Order" %><br />
    <%= f.text_field :orderNum, :size => 3 %>
  </div>
  
  <div class="field">
		<%= f.hidden_field :resumeid %>
  </div>
  <div class="field">
		<%= f.hidden_field :sectionid %>
  </div>
  
  
  <div class="actions">
    <%= f.submit "Update Order" %>
  </div>
<% end %>

app/views/resumesections/edit.html.erb
<h1>Editing Section Order</h1>
<br />

<%= render 'form' %>
<br />
<%= link_to 'Back to View Resume Sections', "/newresumelist/#{@resumesection.resumeid}" %>

app/views/resumesections/list.html.erb
<%= javascript_include_tag :defaults %>
<h1><%= @title %></h1>
<br />
<b><%= link_to "Add Another Section", "/newresume/#{params[:id]}" %></b><br /><br />

<table>
  <tr>
    <th>ID</th>
    <th>Type of Section</th>
    <th>Section Name</th>
	<th>Order</th>
	<th></th>
  </tr>

<% @resumesection.each do |resumesection| %>
  <tr>
    <td><%= resumesection.id %></td>
	<td><%= resumesection.section.typesection %></td>
	<td><%= resumesection.section.title %></td>
	<td><%= resumesection.orderNum %></td>
	<td><%= link_to 'Edit Order', edit_resumesection_path(resumesection) %> | 
	<%= link_to 'Delete', resumesection, :confirm => 'Are you sure?', :method => :delete %></td>
 
  </tr>
<% end %>
</table>
<br />
<%= button_to "Finish Creating Resume", "/viewresume/#{params[:id]}" %>

app/views/resumesections/new.html.erb
<h1><%= @title %></h1>


	<table>
	<tr>
		<th></th><th>Choose Section</th><th>Order #</th><th></th>
	</tr>
	
	
	<% if !@myContact.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>Header</td>
		<td><div class="field"><%= g.collection_select :sectionid, @myContact, :id, :title, :prompt => " ", :style => "width:800px;" %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	<% if !@myObjective.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>Objective</td>
		<td><div class="field"><%= g.collection_select :sectionid, @myObjective, :id, :title, :prompt => " " %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	<% if !@myQualifications.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>Qualifications</td>
		<td><div class="field"><%= g.collection_select :sectionid, @myQualifications, :id, :title, :prompt => " " %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	<% if !@myEducation.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>Education</td>
		<td><div class="field"><%= g.collection_select :sectionid, @myEducation, :id, :title, :prompt => " " %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	<% if !@mySkills.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>Skills</td>
		<td><div class="field"><%= g.collection_select :sectionid, @mySkills, :id, :title, :prompt => " " %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	<% if !@myEmplHistory.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>Employment History</td>
		<td><div class="field"><%= g.collection_select :sectionid, @myEmplHistory, :id, :title, :prompt => " " %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	
	<% if !@myListRef.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>References</td>
		<td><div class="field"><%= g.collection_select :sectionid, @myListRef, :id, :title, :prompt => " " %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	<% if !@myOther.blank? %>
	<tr>
		<%= form_for(@resumesection) do |g| %>
		<%= render 'shared/error_messages', :object => g.object %>
		<td>Other</td>
		<td><div class="field"><%= g.collection_select :sectionid, @myOther, :id, :title, :prompt => " " %></div></td>
		<td><div class="field"><%= g.text_field :orderNum, :size => 3 %></div></td>
		<td><div class="actions">
		<%= g.submit "Add", :disable_with => "Submitted" %></div></td>
			<div class="field">
				<%= g.hidden_field :resumeid, :value => params[:id] %>
			</div>
		<% end %>
	</tr>
	<% end %>
	
	
	</table>

  <%= link_to "See Current Sections", "/newresumelist/#{params[:id]}"%>

app/views/resumesections/show.html.erb
<h1><%= @title %></h1>
ID: <%= @resumesection.id %> | Resume ID: <%= @resumesection.resumeid  %> | Section ID: <%= @resumesection.sectionid %> |
Order #: <%= @resumesection.orderNum %> 