config/routes.rb
RoundfileApp::Application.routes.draw do

root :to => 'pages#home'

  resources :sections
  resources :users
  resources :resumes
  resources :resumesections
  resources :comments
  resources :ratings
  resources :sessions, :only => [:new, :create, :destroy]

	
	match '/newsection',  :to => 'sections#new'
	match '/mysections',  :to => 'sections#mysections'
	match '/newresume',  :to => 'resumes#new'
	match '/viewresume/:id',  :to => 'resumes#show'
	match '/newresume/:id', :to => 'resumesections#new'
	match '/newresumelist/:id', :to => 'resumesections#list'
	match '/newresume/:id/:message', :to => 'resumesections#new'
	match '/myresumes',  :to => 'resumes#myresumes'
	match '/signup',  :to => 'users#new'
	match '/signin',  :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/newcomment/:id',  :to => 'comments#new'
	match '/newcomment/:id/:message', :to => 'comments#new'
	match '/newrating/:id',  :to => 'ratings#new'
	match '/newrating/:id/:score', :to => 'ratings#new'
	match '/userresumes', :to => 'resumes#userres'
	match '/userresumes/:id/', :to => 'resumes#userres'
	
	

end

app/models/section.rb
class Section < ActiveRecord::Base
	attr_accessible :typesection, :content, :userid, :title
	
	belongs_to :user, :class_name => 'User', :foreign_key => 'userid'
	has_many :resumesection, :class_name => 'Resumesection', :dependent => :destroy, :foreign_key => 'sectionid'
		#belongs_to :resumesection

	validates :typesection, :presence => true
	validates :content, :presence => true
	validates :userid, :presence => true
	validates :title, :presence => true
end


# == Schema Information
#
# Table name: sections
#
#  id          :integer         not null, primary key
#  typesection :string(255)
#  content     :string(255)
#  userid      :integer
#  created_at  :datetime
#  updated_at  :datetime
#  title       :string(255)
#

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  
  def show
	@section = Section.find(params[:id])
	@title = "View Section"
  end
  
  def new
	@title = "Create a Section"
	@section = Section.new
  end
  
  def create
	#@userID = User.find_by_userid(current_user.userid)
	
    @section = current_user.sections.build(params[:section])
    if @section.save
      #sign_in @user
      flash[:success] = "Section created!"
      redirect_to @section
    else
      @title = "Create Section"
      render 'new'
    end
  end
  
  def allsections
	@title = "All Sections"
	@section = Section.all
	
	#code from DEMO APP
	respond_to do |format|
      format.html
      format.xml  { render :xml => @section }
    end
  end
	
  def mysections
	@title = "My Sections"
	@section = Section.find_all_by_userid(current_user.id, :order => "typesection")
	
	
	#code from DEMO APP
	respond_to do |format|
      format.html 
      format.xml  { render :xml => @section }
    end
  end
  
  
  
  def edit
	@title = "Edit Section"

    @section = Section.find(params[:id])
  end
  
  def update
	@title = "Edit Section"

    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to(@section, :notice => 'Section was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @section.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @section = Section.find(params[:id])
    @section.destroy
	
	#@resumesection = Resumesection.destroy_all_by_sectionid(params[:id])
	
	
	redirect_to :action => 'mysections'
    #respond_to do |format|
     # format.html { redirect_to(mysections_url) }
     # format.xml  { head :ok }
    #end
  end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	    <%= f.label "Type of Section" %><br /> 
		<%= f.text_field :typesection , :readonly=> true %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/allsections.html.erb
<h1><%= @title %></h1>

<table>
  <tr>
    <th>Type</th>
    <th>Content</th>
    <th>User ID</th>
  </tr>

<% @section.each do |section| %>
  <tr>
    <td><%= section.typesection %></td>
    <td><%= section.content %></td>
    <td><%= section.userid %></td>
  </tr>
<% end %>
</table>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>
<br />
<%= render 'form' %>

<%= link_to 'Back to View Section', @section %>

app/views/sections/mysections.html.erb
<%= javascript_include_tag :defaults %>

<h1><%= @title %></h1>
<br />
<% if !@section.blank? %>
<table>
  <tr>
    <th>Type</th>
    <th>Title</th>
	<th>Actions</th>
  </tr>


<% @section.each do |section| %>
  <tr>
    <td><%= section.typesection %></td>
    <td><%= section.title %></td>
	<td><% if current_user.id == section.userid %>
		<%= link_to 'View', section_url(section) %> | <%= link_to 'Edit', edit_section_path(section) %> | 
		<%= link_to 'Destroy', section, :confirm => 'Are you sure?', :method => :delete %>
	<% end %></td>
 
  </tr>

<% end %>
</table>
<% else %>
	You have not created any sections.
<% end %>

app/views/sections/new.html.erb
<h1><%= @title %></h1>
<br />
<%= form_for(@section) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label "Type of Section" %><br />
    <%= f.select :typesection, [['Contact'],['Objective'],['Qualifications'],['Education'],['Skills'],['Employment History'],['List of References'],['Other']], :prompt => " " %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="field">
	<%= f.hidden_field :userid, :value => current_user.id %>
	</div>
  
  <div class="actions">
    <%= f.submit "Create Section", :disable_with => "Submitting..." %>
  </div>
<% end %>

app/views/sections/show.html.erb
<%= javascript_include_tag :defaults %>
<h1><%= @title %></h1>
<br />
<table>
<tr><th>Type</th><th>Creator</th><th>Title</th></tr>
<tr>
<td><%= @section.typesection %></td>
<td> <%= link_to "#{@section.user.name}", user_path(@section.userid) %></td>
<td> <%= @section.title %></td></tr>
</table>

<% if current_user.id == @section.userid %>

<%= link_to 'Edit', edit_section_path(@section) %> | <%= link_to 'Destroy', @section, :confirm => 'Are you sure?', :method => :delete %>
 
<% end %><br /><br />

<h3>Content:</h3> <br />
<%= raw @section.content %>