config/routes.rb
RoundfileApp::Application.routes.draw do

root :to => 'pages#home'

  resources :sections
  resources :users
  resources :resumes
  resources :resumesections
  resources :comments
  resources :ratings
  resources :sessions, :only => [:new, :create, :destroy]

	
	match '/newsection',  :to => 'sections#new'
	match '/mysections',  :to => 'sections#mysections'
	match '/newresume',  :to => 'resumes#new'
	match '/viewresume/:id',  :to => 'resumes#show'
	match '/newresume/:id', :to => 'resumesections#new'
	match '/newresumelist/:id', :to => 'resumesections#list'
	match '/newresume/:id/:message', :to => 'resumesections#new'
	match '/myresumes',  :to => 'resumes#myresumes'
	match '/signup',  :to => 'users#new'
	match '/signin',  :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/newcomment/:id',  :to => 'comments#new'
	match '/newcomment/:id/:message', :to => 'comments#new'
	match '/newrating/:id',  :to => 'ratings#new'
	match '/newrating/:id/:score', :to => 'ratings#new'
	match '/userresumes', :to => 'resumes#userres'
	match '/userresumes/:id/', :to => 'resumes#userres'
	
	

end

app/models/resume.rb
class Resume < ActiveRecord::Base

attr_accessible :name, :userid
	
	belongs_to :user, :class_name => 'User', :foreign_key => 'userid'
	has_many :section
	has_many :resumesection, :class_name => 'Resumesection',:dependent => :destroy, :foreign_key => 'resumeid'	
	
	validates :name, :presence => true
	validates :userid, :presence => true

end

# == Schema Information
#
# Table name: resumes
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  userid     :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  
  def show
	@resume = Resume.find(params[:id])
	
	
	@resumesection = Resumesection.find_all_by_resumeid(params[:id], :order => "orderNum")
	@comment = Comment.find_all_by_resumeid(params[:id], :order => "created_at")
	@rating = Rating.find_all_by_resumeid(params[:id], :order => "created_at")
	@usercurrentrating = Rating.find_by_resumeid_and_userid(params[:id], current_user.id)
	
	#@section = Section.find(:all)
	
	@title = "View Resume"
  end
  
  def new
    @title = "Name Your Resume"
	@resume = Resume.new
  end
  
  def create	
    @resume = current_user.resumes.build(params[:resume])
    if @resume.save
      flash[:success] = "Resume created!"
      redirect_to "/newresume/#{@resume.id}"
	else
      @title = "Create Resume"
      render 'new'
    end
  end
  
  def allresumes
	@title = "All Resumes"
	@resume = Resume.all
	
	#code from DEMO APP
	respond_to do |format|
      format.html
      format.xml  { render :xml => @resume }
    end
  end
	
  def myresumes
	@title2 = "My Resumes"
	@resume = Resume.find_all_by_userid(current_user.id)
	@user = User.find(current_user.id)
	@title = @user.name
	
	
	#code from DEMO APP
	respond_to do |format|
      format.html 
      format.xml  { render :xml => @resume }
    end
  end
  
  def userres
	@title = "Find Resumes by User"
	@user = User.find(:all)
	@resume = Resume.find_all_by_userid(params[:id])
	if (!params[:id].blank?)
		@userselected = User.find(params[:id])
		@title2 = "#{@userselected.name}'s Resumes"
	else
		@title2 = " "
	end
	
  end
  
  def edit
	@title = "Edit Resume"
    @resume = Resume.find(params[:id])
  end
  
  def update
	@title = "Edit Resume"

    @resume = Resume.find(params[:id])

    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to("/newresumelist/#{@resume.id}", :notice => 'Resume Title was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @resume.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
	
	
	redirect_to :action => 'myresumes'

  end


  
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	    <%= f.label "Resume Title" %><br /> 
		<%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Submit Title...", :disable_with => "Submitting..."  %>
  </div>
<% end %>

app/views/resumes/allresumes.html.erb
<h1><%= @title %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>User ID</th>
  </tr>

<% @resume.each do |resume| %>
  <tr>
    <td><%= resume.name %></td>
    <td><%= resume.userid %></td>
  </tr>
<% end %>
</table>

app/views/resumes/edit.html.erb
<h1>Editing Resume Title</h1>
<br />


<%= render 'form' %>
<br />
OR
<%= link_to 'Edit Resume Sections List', "/newresumelist/#{@resume.id}" %><br /><br />
<small><%= link_to 'Back to View Resume', @resume %></small>

app/views/resumes/myresumes.html.erb
<%= javascript_include_tag :defaults %>
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>
<br />

<h3><%= @title2 %></h3>
<% if !@resume.blank? %>
<table>
<tr><th> </th> <th> </th></tr>

<% @resume.each do |resume| %>
  <tr>
    <td><%= link_to "#{resume.name}", "/viewresume/#{resume.id}" %></td>
	<td><% if current_user.id == resume.userid %><%= link_to 'View', resume_url(resume) %> | <%= link_to 'Edit', edit_resume_path(resume) %> | <%= link_to 'Destroy', resume, :confirm => 'Are you sure?', :method => :delete %>
	<% end %></td>
 </tr>

	
  
<% end %>
</table>

<% else %>
	You have not created any resumes.
<% end %>

app/views/resumes/new.html.erb
<h1><%= @title %></h1>
<br />

<%= form_for(@resume) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
		<%= f.label "Name" %><br />
		<%= f.text_field :name %>
    </div>
	<div class="field">
	<%= f.hidden_field :userid, :value => current_user.id %>
	</div>
	<div class="actions">
		<%= f.submit "Make section selections...", :disable_with => "Submitting..." %>
		</div>
		<% end %>
	
	

app/views/resumes/show.html.erb
<%= javascript_include_tag :defaults %>
<%= stylesheet_link_tag 'star_rating', :media => 'screen' %>
<h1><%= @title %></h1>
<br />
<b>Resume Name:</b> <%= @resume.name %><br />
Author: <%= link_to "#{@resume.user.name}", user_path(@resume.userid) %><br />
<%= link_to 'Edit Resume', edit_resume_path(@resume) %> | 
<%= link_to 'Delete Resume', @resume, :confirm => 'Are you sure?', :method => :delete %><br />

<br />
<br />
<b><%= link_to "Make a Comment", "/newcomment/#{@resume.id}" %></b><br />
<% if !@usercurrentrating.blank? %>
Your Rating for this resume: 
	<ul class="star-rating">
	
	<% if @usercurrentrating.rating_score == 1 %>
	<li class="current-rating" style="width:20%;">Your Rating was 1/5 Stars.</li>
	<% elsif @usercurrentrating.rating_score == 2 %>
	<li class="current-rating" style="width:40%;">Your Rating was 2/5 Stars.</li>
	<% elsif @usercurrentrating.rating_score == 3 %>
	<li class="current-rating" style="width:60%;">Your Rating was 3/5 Stars.</li>
	<% elsif @usercurrentrating.rating_score == 4 %>
	<li class="current-rating" style="width:80%;">Your Rating was 4/5 Stars.</li>
	<% elsif @usercurrentrating.rating_score == 5 %>
	<li class="current-rating" style="width:100%;">Your Rating was 5/5 Stars.</li>
	<% else %>
	<li class="current-rating" style="width:0%;">Your Rating was 0/5 Stars.</li>
	<% end %>

	<li> <b></b> </li>
	<li><b></b></li>
	<li><b></b></li>
	<li><b></b></li>
	<li><b></b></li>
	</ul>
<% else %>
Rate Resume: 
	<ul class="star-rating">

	<li class="current-rating" style="width:0%;">Currently 0/5 Stars.</li>

	<li><a href="/newrating/<%= @resume.id %>/1" title="1 star out of 5" class="one-star">1</a></li>

	<li><a href="/newrating/<%= @resume.id %>/2" title="2 stars out of 5" class="two-stars">2</a></li>

	<li><a href="/newrating/<%= @resume.id %>/3" title="3 stars out of 5" class="three-stars">3</a></li>

	<li><a href="/newrating/<%= @resume.id %>/4" title="4 stars out of 5" class="four-stars">4</a></li>

	<li><a href="/newrating/<%= @resume.id %>/5" title="5 stars out of 5" class="five-stars">5</a></li>

</ul>
<% end %>


<br />
<div id= "resume">
<p>
<br /><br />
<% @resumesection.each do |resumesection| %>

	<%= raw resumesection.section.content %><br />
<% end %>

<br />
<p>
</div>	



<br />
<br />
<bf />

<div id= "ratecomment">
	
		
	<div id = "rate">
	<h3>Ratings</h3>
		<% if !@rating.blank? %>
		
		<br />
		<% @rating.each do |rating| %>
			<%= rating.user.name %> : 
			
			
	<ul class="star-rating">
	
	<% if rating.rating_score == 1 %>
	<li class="current-rating" style="width:20%;">Your Rating was 1/5 Stars.</li>
	<% elsif rating.rating_score == 2 %>
	<li class="current-rating" style="width:40%;">Your Rating was 2/5 Stars.</li>
	<% elsif rating.rating_score == 3 %>
	<li class="current-rating" style="width:60%;">Your Rating was 3/5 Stars.</li>
	<% elsif rating.rating_score == 4 %>
	<li class="current-rating" style="width:80%;">Your Rating was 4/5 Stars.</li>
	<% elsif rating.rating_score == 5 %>
	<li class="current-rating" style="width:100%;">Your Rating was 5/5 Stars.</li>
	<% else %>
	<li class="current-rating" style="width:0%;">Your Rating was 0/5 Stars.</li>
	<% end %>

	<li> <b></b> </li>
	<li><b></b></li>
	<li><b></b></li>
	<li><b></b></li>
	<li><b></b></li>
	</ul>
			<% if current_user.id == rating.userid %> 
				<%= link_to 'Delete', rating, :confirm => 'Are you sure?', :method => :delete %>
			<% end %>
			<br /><br />
		<% end %>
		<% else %>
		
		There are no ratings for this resume yet.
		<br /><br /><br /><br />
		<% end %>
	</div>
	
	
	<div id= "comment">
	<h3>Comments</h3>
		<% if !@comment.blank? %>
		
		<br />
		<% @comment.each do |comment| %>
			<%= comment.comment %><br />
			<b>Author:</b> <%= link_to "#{comment.user.name}", user_path(comment.user.id) %> <br />
			<% if current_user.id == comment.userid %>
				<%= link_to 'Edit', edit_comment_path(comment) %> | 
				<%= link_to 'Delete', comment, :confirm => 'Are you sure?', :method => :delete %>
			<% end %>
			<br /><br />
		<% end %>
		
		<% else %>
		
		There are no comments for this Resume yet.
		<br /><br /><br /><br />
		<% end %>
	</div>
	
	
</div>

app/views/resumes/userres.html.erb
<h1><%= @title %></h1>
<br />
<div id = "userres-wrapper">
<div id= "users">
<center><h3>Users</h3></center><br />
	<% @user.each do |user| %>
		<%= link_to "#{user.name}", "/userresumes/#{user.id}" %><br />
	<% end %>
	
</div>

<div id="userres">
	<% if params[:id].blank? %>
		<br />
		Pick a User from the list on the left.
	<% end %>
	
	<% if !params[:id].blank? %>
		<h3><%= @title2 %></h3><br />
		<% @resume.each do |resume| %>
		<%= link_to "#{resume.name}", "/viewresume/#{resume.id}" %><br />
		<% end %>
		<% end %>
	
	<% if @resume.blank? && !params[:id].blank? %>
	
	This user does not have any resumes yet.
	<% end %>
</div>
<br /><br />
</div>
<br />