config/routes.rb
RoundfileApp::Application.routes.draw do

root :to => 'pages#home'

  resources :sections
  resources :users
  resources :resumes
  resources :resumesections
  resources :comments
  resources :ratings
  resources :sessions, :only => [:new, :create, :destroy]

	
	match '/newsection',  :to => 'sections#new'
	match '/mysections',  :to => 'sections#mysections'
	match '/newresume',  :to => 'resumes#new'
	match '/viewresume/:id',  :to => 'resumes#show'
	match '/newresume/:id', :to => 'resumesections#new'
	match '/newresumelist/:id', :to => 'resumesections#list'
	match '/newresume/:id/:message', :to => 'resumesections#new'
	match '/myresumes',  :to => 'resumes#myresumes'
	match '/signup',  :to => 'users#new'
	match '/signin',  :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/newcomment/:id',  :to => 'comments#new'
	match '/newcomment/:id/:message', :to => 'comments#new'
	match '/newrating/:id',  :to => 'ratings#new'
	match '/newrating/:id/:score', :to => 'ratings#new'
	match '/userresumes', :to => 'resumes#userres'
	match '/userresumes/:id/', :to => 'resumes#userres'
	
	

end

app/views/layouts/_header.html.erb
<header>
  <div id="wrapper">
		<div id="header-wrapper">
			<div id="header">
					<div id="logo">
					<h1><%= link_to "Round File", root_path %></h1>
					<p>Catch Phrase goes Here!</p>
					</div>
			</div>
		</div>
	
	<div id="menu-wrapper">
		<div id="menu">
		<ul>		
		<% if signed_in? %>
		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<li><%= link_to "Home", root_path %></li>		
		<% else %>
		<li><%= link_to "Sign in", signin_path %></li>
		<li><%= link_to "Home", root_path %></li>
		<% end %>
		</ul>
		</div>
		
	</div>
</div>
  
 <!-- <div id="menu-wrapper">
	<div id="menu">
		<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "User Resumes", "#"%></li>
		<% if signed_in? %>
		<li><%= link_to "Profile", current_user %></li>
		<li><%= link_to "New Section", "/newsection" %></li>
		<li><%= link_to "New Resume", "/newresume" %></li>
		<li><%= link_to "My Sections", "/mysections" %></li>
		<li><%= link_to "My Resumes", "/myresumes" %></li>
		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
		<li><%= link_to "Sign in", signin_path %></li>
		<% end %>
		</ul>
		</div>
		
  </div> -->
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-wrapper">
	<div id="sidebar">
		<ul>		
		<% if signed_in? %>

		<li><%= link_to "My Resumes", "/myresumes" %></li>
		<li><%= link_to "New Resume", "/newresume" %></li>		
		<li><%= link_to "New Section", "/newsection" %></li>
		<li><%= link_to "My Sections", "/mysections" %></li>
		<li><%= link_to "User Resumes", "/userresumes"%></li>
		
		<% end %>
		</ul>
		</div>
		
  </div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'star_rating', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div id="wrapper">
	  <div id= "sidebar-wrapper">
		<%= render 'layouts/sidebar' %>
	  </div>
		<div id="page">
			<div id="page-bgtop">
				<%= yield %>
				</br>
				</br>
			</div>
		</div>
			
	  </div>
  </body>
  
</html>